CREATE TABLE client (
	id INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	personCount TINYINT(1) UNSIGNED NOT NULL,
	email VARCHAR(100) NULL DEFAULT NULL,
	phone VARCHAR(24) NULL DEFAULT NULL,
	notice TEXT,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE occupancy (
	day DATE NOT NULL,
	client_id INT(1) UNSIGNED NOT NULL,
	PRIMARY KEY (day),
	CONSTRAINT fk_client_id FOREIGN KEY (client_id) REFERENCES client (id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
